### PR TITLE
Add selection order badges to multi-card select actions

### PR DESCRIPTION
**Pull request by andrewd18**
### Summary of Changes
When you are prompted to select multiple cards, and you select one or more cards, the cards get a badge that indicate the order in which you selected them.

image

### Benefits
- You can tell the order in which things will be seeded, such as dilemmas.

### Risks
- None that I am aware of; this is a new class and attribute on an existing element; no existing data was changed.

### Testing
- Manual.
- Verified that resetting the choice removes all the badges and data.
- Verified that selecting some cards, then deselecting them removes the badge and recalculates the other numbers if needed.
- Verified that the number stays pretty much where it's supposed to when the browser size changes the size of the card.

### Possible improvements to this PR
- This is a quick fix for MVP. There might be an opportunity to use the existing token overlay and add a new type of token, but I don't understand where that data is coming from and until it's unit tested I'd rather add something new than break something that currently works.
- Badge color matches the existing selected card outline color; easy to change in the CSS if we hate it.

### CODE REVIEW

**Comment by datanoh** [comment]
Added some recent updates from main to this branch; it now has the 1E Debug game format. This format doesn't require 6 missions, so you can get to the dilemma seeding faster.

**Review by datanoh — APPROVED** [review]
I really like this! Looks better than the tokens IMO. "Token" is also a game-specific LotR term, so it wouldn't shock me if there's some background weirdness to using that functionality that neither of us have noticed.

Two thoughts, up to you if you want to address them prior to MVP. I know this is a short-term solution anyway.

1. Looks like the numbers will show up any time CardSelectionDecision is used, is that correct? This is potentially a source of confusion, but I'm not sure it will be a problem for anything in MVP. For example, when you select cards to beam, it uses the CardSelectionDecision. I think it's making the numbers, but we can't see the middle of the cards during that decision anyway. I pushed a change to this branch to include the phase as an attribute when sending the decision XML. When you're seeding dilemmas, decision.getAttribute("phase") = "SEED_DILEMMA".

2. The numbers go 1,2,3 even if you've already stacked "pre-seed" cards for the mission, and you're seeding additional ones. If you have 2 cards already pre-seeded, would it be useful for the seed dilemma badges to go 3,4,5,... instead? I could see an argument either way. Happy to include data in the XML for how many cards are already pre-seeded, *if* you think it's helpful. (A lot of players won't run into this, if they already have their combos figured out ahead of time.)

**Comment by andrewd18** [comment]
> Looks like the numbers will show up any time CardSelectionDecision is used, is that correct? This is potentially a source of confusion

That was intentional - this change scales beyond dilemmas. For example, Borg are going to have to probe a lot and want to return cards to their deck in a specific order. Any time a user has to select more than one card, we should remind them the order they are selecting.

Scrying in Magic: Arena brings up a draggable dialog box which is very cool but not realistic for MVP:

mtg_scry

Order selection in Yugioh: Master Duel just applies a number like I did:

ygo_card_select

> The numbers go 1,2,3 even if you've already stacked "pre-seed" cards for the mission, and you're seeding additional ones. If you have 2 cards already pre-seeded, would it be useful for the seed dilemma badges to go 3,4,5,... instead?

I do not want to do this. The number in the selection is based on the number of cards you've selected during the scope of the current decision. It intentionally resets when you start to make a different decision.

Instead, for the "oh no I forgot how many cards I seeded under [mission]" case, I would like to ensure that the mission view/stacking code is obvious how many cards are under each mission. In Lackey and IRL, I have seen most people either have their combos pre-designed, or are counting the cards in the stack. If by looking at the mission you can obviously tell it only has 2 cards under it when you wanted 3, I think that solves this case.

**Comment by datanoh** [comment]
That all sounds good to me! Do we want a number indicator on missions to indicate how many cards are underneath then? And if so, would that be an MVP goal?

**Pull request merged**
