### PR TITLE
Promisify comms.getCollections and comms.getSets

### LINKED ISSUE #93: Available cards in deck builder don't update when you change formats
If you change the game format in the upper-left dropdown box:

image

The available cards on the right don't update accordingly. Shown below, the format has been changed to "2E All" but all the cards are still 1E cards.

image

### PR DESCRIPTION
**Pull request by andrewd18**
### Summary of Changes
This is a first of a long series of overhauls to begin fully unit testing our comms stack. This PR:

1. Enhances the NodeJS test environment to support testing using JQuery UI functions.
2. Converts comms.getCollections and comms.getSets from their callback functions to ES6 fetch() functions that use Promises.
3. Creates unit tests for comms.getCollections and comms.getSets and ensures they are 100% unit tested.
4. Adds an eslint config file to perform static analysis and report issues lurking in the JS, where possible. Should be editor-agnostic, if the editor can use eslint.

### Benefits
- Sets a new precedent for testing Comms functions and tests - we can write tests that pretend to be the server and verify the JS side performs the correct actions.
- Clarifies order of operations by removing callbacks - promise functions return values rather than calling another function which calls another function, etc.
- Moves logic that used to be scattered around the code base into clearly defined areas of responsibility.
- Closes #93 

### Risks
Promises are inherently asynchronous. The callback-style functions we use elsewhere are a synchronous, blocking design, meaning that if the server is delayed in the getCollections call, the UI would not render until the response arrived. I am mimicking that here with the promise.then() design in cardFilter.js, and it was working fine when I tested it. However:
* The DeckBuilder constructor calls the CardFilter constructor. CardFilter previously called a synchronous comms call which is now asynchronous. This could cause CardFilter to act funny until the server resolves. It was working fine in manual testing.

### Testing
- Fully automated. As of the time of this PR, comms.getCollections and comms.getSets are 100% unit tested. Comms as a whole is 19% unit tested and cardFilter is 74% unit tested.
- Messed around in the Deck Builder to verify it continued to work as intended.

### Possible improvements to this PR
- To completely eliminate the risk above, the entire deck builder UI (and hall and game UI and anything else that uses comms :scream:   ) need to be redesigned. This is skipped here for MVP-and-time reasons. The changes are:
  - Have constructors return empty-but-functional objects, like empty combo boxes.
  - Any place where we would do a comms call in a constructor, move that out into a post-object-instantiation setup() call or something similar, since that will be an async call.

### Other notes
- I was really hoping this would be a bigger PR where I could convert a lot of comms in one go, but every time I made a change to the comms stack it would ripple up with async calls and break other things. I will need to continue to do this piece by piece.

### CODE REVIEW

**Comment by andrewd18** [comment]
@datanoh The changes only affect DeckBuilder, so to test, please mess around in there with the filters and drop-downs and verify it still works like you'd expect.

**Review by datanoh — COMMENTED** [review]
Nice! Just tested out the interface, didn't look at the code much. As far as I can tell, there are no changes to the functionality. Except that it no longer shows the Premiere expansion cards only by default, so thank you for that!

While reviewing, I noticed Issue #93. Not caused by this update, but it might be easy to fix while you're in there. Up to you.

**Comment by andrewd18** [comment]
#93 was broken on main but the async change here makes it more noticeable. On main, the card filter sets drop-down is cleared, forcing you to switch it manually. On this branch, the card filter sets drop-down fills with 2E as an option but requires you to change it manually before the card sets update (and you can't change it manually since there is only one 2E format).

I will fix this on this branch before merging it.

**Comment by andrewd18** [comment]
@datanoh OK, try it now. I think I got it. :)

**Comment by datanoh** [comment]
Beautiful, worked like a charm. Thanks!

**Pull request merged**
