### PR TITLE
Assign Mission Specialists

### PR DESCRIPTION
**Pull request by datanoh**
Added a dynamic selection feature to the server side.

At the moment this will only be triggered by using the download action of Assign Mission Specialists. When the arbitrary cards decision is sent to the client, it will include the parameter "combinations".

"combinations" is a JSON string converted from a map object. Each map key is the decision cardId for a selectable card by the decision, and the value is a list of decision cardId's that are compatible.

For example, say you have a [NA] outpost in play and want to download mission specialists. You have Darian Wallace (Fed), Simon Tarses (Fed), Narik (NA), and 2 Takkets (Rom) in your deck. The mission specialists have to be different cards and compatible with each other, so the "combinations" parameter would look something like:

- Darian Wallace: Narik, Simon Tarses
- Narik: Darian Wallace, Simon Tarses, Takket1, Takket2
- Takket1: Narik
- Simon Tarses: Darian Wallace, Narik
- Takket2: Narik

For the client side, at the moment it would be ideal if the selectable card options changed after each selection was made. For example, if I pick Takket 1, the only card that would still be selectable as a second card would be Narik.

Is that something that's doable?

### CODE REVIEW

**Comment by andrewd18** [comment]
As we discussed over chat, yes, this is possible. I'll need to make a custom UI for it. I would appreciate if the incoming game event had a unique name like SelectCardsFromLimitedCombinations or something.

I can't yet test what you're sending me since playing AMS is crashing the server with:
```
03:01:47.586 [nioEventLoopGroup-3-34] ERROR com.gempukku.stccg.game.CardGameMediator - Error processing game decision
java.lang.NullPointerException: Cannot invoke "com.gempukku.stccg.gamestate.MissionLocation.isSpace()" because "currentLocation" is null
	at com.gempukku.stccg.cards.blueprints.Blueprint155_060.getSkills(Blueprint155_060.java:28) ~[web.jar:?]
	at com.gempukku.stccg.cards.physicalcard.PersonnelCard.getSkills(PersonnelCard.java:76) ~[web.jar:?]
	at com.gempukku.stccg.cards.blueprints.Blueprint109_063.getValidResponses(Blueprint109_063.java:50) ~[web.jar:?]
	at com.gempukku.stccg.cards.physicalcard.AbstractPhysicalCard.getOptionalAfterTriggerActions(AbstractPhysicalCard.java:268) ~[web.jar:?]
	at com.gempukku.stccg.actions.EffectResult.createOptionalAfterTriggerActions(EffectResult.java:94) ~[web.jar:?]
	at com.gempukku.stccg.processes.TurnProcedure.lambda$0(TurnProcedure.java:33) ~[web.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at com.gempukku.stccg.processes.TurnProcedure.carryOutPendingActionsUntilDecisionNeeded(TurnProcedure.java:33) ~[web.jar:?]
	at com.gempukku.stccg.game.DefaultGame.carryOutPendingActionsUntilDecisionNeeded(DefaultGame.java:212) ~[web.jar:?]
	at com.gempukku.stccg.game.CardGameMediator.playerAnsweredNew(CardGameMediator.java:235) ~[web.jar:?]
	at com.gempukku.stccg.async.handler.GameRequestHandler.updateGameState(GameRequestHandler.java:91) ~[web.jar:?]
	at com.gempukku.stccg.async.handler.GameRequestHandler.handleRequest(GameRequestHandler.java:64) ~[web.jar:?]
	at com.gempukku.stccg.async.handler.RootUriRequestHandler.handleRequest(RootUriRequestHandler.java:74) ~[web.jar:?]
	at com.gempukku.stccg.async.GempukkuHttpRequestHandler.channelRead0(GempukkuHttpRequestHandler.java:82) ~[web.jar:?]
	at com.gempukku.stccg.async.GempukkuHttpRequestHandler.channelRead0(GempukkuHttpRequestHandler.java:1) ~[web.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[web.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[web.jar:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[web.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[web.jar:?]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[web.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[web.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[web.jar:?]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[web.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[web.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868) ~[web.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[web.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[web.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[web.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[web.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[web.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[web.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[web.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[web.jar:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by andrewd18** [comment]
This branch also needs to either be rebased on `main` or have `main` merged into it, as it needs a chat.js fix in `appendServerCommunicationProblemMessage()` to avoid a UI crash.

**Comment by datanoh** [comment]
@andrewd18 I'll merge the main edits into this branch and fix the Geordi bug you ran into.

**Comment by datanoh** [comment]
@andrewd18 The new decision type is CARD_SELECTION_FROM_COMBINATIONS.

**Comment by andrewd18** [comment]
Added a unique UI element so we can modify it. Gave it selection order badges and validate against the max.

TODO: That UI needs to read the combinations and disable the Done button or otherwise warn if the combination is invalid. That code should happen inside `processButtons`.

**Comment by datanoh** [comment]
Updated the back-end so that all cards selected will be downloaded

**Comment by andrewd18** [comment]
Two things:

1. Can you send the combinations to the UI with a name of "combinations" and a value of the JSON? I can't use the built-in parameter code when it's sent like this and I'd rather not write another set.  It should look like the other parameters here:

image

2. Can you add Husnock Outpost to the blueprints? I'd like to test using the exact combinations you defined in this PR. Right now I don't have a facility where I could cause non-compatible plays.

**Comment by datanoh** [comment]
#2 should be fixed now, as well as the duplicate "combinations" items.

I added Husnock Outpost. It should seed correctly, but it won't allow you to seed Husnock Ship. Also bear in mind for AMS that the two specialists have to be _different_ - so an easy check of the combinations would just be to add multiple copies of some mission specialists in your deck.

For the JSON structure, let's say we've got four mission specialists in your deck, and Fed Outpost in play:
- temp0: Darian Wallace
- temp1: Simon Tarses
- temp2: Narik
- temp3: Simon Tarses

Any combination of 2 is acceptable in this case, _except_ two Simons. It would look like this:

```
{
    "temp0": [
      "temp1",
      "temp2",
      "temp3"
    ],
    "temp1": [
      "temp0",
      "temp2"
    ],
    "temp2": [
      "temp0",
      "temp1",
      "temp3"
    ],
    "temp3": [
      "temp0",
      "temp2"
    ]
...

temp0 can be selected with either of temp1 and temp3, but not with both of them, because temp1's children don't include temp3. So every time you select or deselect a card, the list of selectable cards should change to include only the elements that are children of all the currently selected cards. This should be infinitely scalable on the client side.

I'm not overly attached to this approach, let me know if there'd be something more helpful.

**Comment by andrewd18** [comment]
Ah, yes, this all makes sense now. Thanks!

**Comment by andrewd18** [comment]
Please retest; this is now working for me. The UI:
- Won't let you select two of the same card
- Won't let you select more cards than the max, even if they're all compatible (try 2+ NA's)
- Won't let you pick incompatible cards, like Roms and Feds
- Dynamically changes the selectable cards based on compatibility

**Review by andrewd18 — APPROVED** [review]

**Comment by datanoh** [comment]
Love this! Works great on my end.

Visually it can be a little hard to tell the difference between selected / selectable / unselectable. What would you say to:
- Selected - bright color border
- Selectable - dimmer color border (maybe gray?)
- Unselectable - no border, and tweak the image settings (lower opacity? or brightness? something to make it a little more ghosty, if that makes sense)

**Comment by andrewd18** [comment]
> Visually it can be a little hard to tell the difference between selected / selectable / unselectable. What would you say to:
> 
> Selected - bright color border (the current color is fine)
> Selectable - significantly dimmer color border (or maybe gray?)
> Unselectable - no border, and tweak the image settings (maybe lower brightness? is that something that can be tweaked in CSS? thinking of something that would make it fade into the background just a wee bit)

Unselectable has no border, Selectable is yellow border, Selected is green border with number if applicable. This is currently how all theming settings behave regardless of where they are in the UI: playing cards from hand, activating cards on the spaceline, or in other dialogs. 

Would you like me to change the theming across the entire UI or just in this dialog box?

**Comment by datanoh** [comment]
It hasn't seemed like an issue thus far, but I haven't used the download action in a while. Once we've got the potential for 10+ cards in the dialog box, it'd be a nice user-friendly touch to help them quickly find what they're looking for.

I don't feel like it would be needed for selecting cards from hand, etc. - but I'm not sure it would be a _bad_ thing either. What do you think?

**Comment by andrewd18** [comment]
OK I'll take a mixed approach. What do you think?

Across-the-game changes:
- "Can be clicked" border is now TrekCCG Blue(tm)
- "Is clicked" border is a tetradic complimentary green

In this dialog:
- "Cannot be clicked" gets grayed out.
- "Cannot be clicked" gets a change in pointer to a not-allowed icon (see Takket on right).

image

**Comment by datanoh** [comment]
I dig it. Had to go look up the word "tetradic".

A little on the fence about the "not-allowed" icon, just because you can still technically interact with that card (right-click to magnify). Maybe we keep it for now and see how we feel about it as time goes on?

Anything else you want to do on this branch?

**Comment by andrewd18** [comment]
What, doesn't everyone have color theory memorized?

I can remove the not-allowed icon, easy undo.

TODO: Still need to go through the other dialogs and add the gray-out for
the "reached max selectable" scenario we talked about yesterday.

**Comment by andrewd18** [comment]
Arbitrary card decision dialog now respects the server-sent max and adds selection order. In the pic below I hacked the max so that it only allowed 2 doorways since it was easy to test.

image

**Comment by andrewd18** [comment]
@datanoh Please re-test, let me know if you're happy with the Arbitrary and Combinations dialogs. If so, resolve the merge conflicts and deliver it to `main`; if not, post here. Thanks!

**Comment by andrewd18** [comment]
Sure, I can add Select All and Select None to Arbitrary. No, using
Combinations for everything is not useful to me. I want more dialogs with a
clear purpose, not fewer dialogs with multiple conflicting purposes. The
"reuse code" part will come with the React overhaul where I can write
standalone components that can go into multiple dialogs but still have
single, testable behavior.

**Comment by datanoh** [comment]
@andrewd18 Sounds good to me. FWIW on the server side, I'd like to move towards having _fewer_ decision classes. It's already a bit confusing picking the right decision class. I think this isn't a question of client _dialog_, but just sending the client enough information that it can make its own decision about which dialog to use. Does that sound right to you? Either way, not urgent to me. Probably not worth messing with prior to MVP.

Do you want to make the "Select All" / "Select None" change on this branch? Or is that a later feature? (i.e. should we close this branch now?)

**Pull request merged**
