### PR TITLE
Stacked / Place on Mission

### PR DESCRIPTION
**Pull request by datanoh**
Primary changes made
- Removed "STACKED" zone from client and server. It was already not in use; no cards were ever being assigned to the STACKED zone. (@andrewd18 - can you review the changes made to gameAnimations.js?)
- Removed generateSnapshot method from PhysicalCard classes; these were all using the "stacked" functionality (just passing the empty list back and forth). Long-term, the generateSnapshot functionality will be removed. It was never 100% working, and the current plan is to handle gamestate load/save with JSON strings.
- Added a very limited-functionality Friendly Fire card implementation that just places on mission when encountered.

### CODE REVIEW

**Comment by datanoh** [comment]
@andrewd18 Whenever you have time, could you take a look and let me know if this will work for implementing the Z-levels for "place on mission"?

The current setup is still coming through the game event classes. Any game event that includes the card data will include the attribute "placedOnMission" if the card is placed on a mission, with the parameter set to true. The "targetCardId" attribute in those cases will be the cardId of the top mission card for the location.

Ideally this would be caught for the "put card into play" and "move card" game animations on the client side.

The card Friendly Fire is in this PR. It doesn't implement any of its gametext except the "Place on mission" part, so if an AT or crew encounters it, it should just go right to the mission with no additional effects.

Let me know what you think, if there's a better way to send this information to the client, etc. Thanks!

**Comment by datanoh** [comment]
For reference, the "targetCardId" field that comes from the server currently represents three different things:
- "Stacked on" card - this is only used for shared missions. The top mission will have targetCardId = the bottom mission's cardId.
- "Attached to" card - this is used in a broad variety of cases, including the cardId of a mission whose planet surface the card is on, or the cardId of a facility the ship is docked at
- "Placed on" mission - new in this PR; cardId of the mission the card is placed on top of

This all feels pretty messy to me. It's entirely for the benefit of the client, so just let me know if there's a more helpful hierarchy.

**Comment by andrewd18** [comment]
> This all feels pretty messy to me. It's entirely for the benefit of the client, so just let me know if there's a more helpful hierarchy.

I think this speaks to the long-term value of defining the game board in a UI-agnostic way. There's two ways to do it, either a nested, semantic heirarchy (think XML or classes):
```
spaceline_locations [
    spaceline location:
        missions: [
            mission:
                hidden_dilemmas: [
                ]
                visible_dilemmas: [
                ] 
                objectives: [
                ]
        ]
        ships [
            ship:
                name: "Enterprise"
                id: 7036
                personnel: [
                ]
                tactics_damage: [
                ]
        ]
        facilities: [
            facility:
                name: "Empok Nor"
                docked_ships: [
                    ship:
                        name: "USS Galaxy"
                        personnel: [
                        ]
                        tactics_damage: [
                        ]
                ]
        ]
]
etc.
```

or the flat, relational database, everything-as-a-list but cross referenced by IDs way:
```
spaceline_locations: [
    spaceline_location:
        name: "Risa Shore Leave"
        id: 2029
]
facilities: [
    facility:
        name: "Empok Nor"
        id: 1105
]
ships: [
    ship:
        name: "Enterprise"
        id: 7036
        at_location: 2029 // this could include facility IDs to mean "docked"
]
etc.
```

The nested way usually maps nicely to how classes work in your code. This usually means you have each parent object call `children.each.to_json()` kind of functions on each of the child items to iterate through the tree. Another drawback is that it causes a lot of visual duplication in the output.

The relational database way still has each item in the lists match your class, but the nesting isn't obvious. However, because you can make changes to one list without affecting the others, there's a lower risk of the code of one thing accidentally affecting the other. Here you just go through each of the ships, missions, etc. classes in your codebase and call `to_json()` on each item in the array.

I loosely prefer solution 2 (flat), but I do not care which one we go with so long as we define it and agree on it. Both of these are easy enough to maintain if you have unit and functional tests that verify your code outputs what it is supposed to in various edge cases.

**Review by andrewd18 — APPROVED** [review]
No concerns about the JS changes.

**Comment by andrewd18** [comment]
> The "place on mission" info is still coming through the game event classes. Any game event that includes the card data will include the attribute "placedOnMission" if the card is placed on a mission, with the parameter set to true. The "targetCardId" attribute in those cases will be the cardId of the top mission card for the location.
> ...
> 
>*    "Stacked on" card - this is only used for shared missions. The top mission will have targetCardId = the bottom mission's cardId.
>*    "Attached to" card - this is used in a broad variety of cases, including the cardId of a mission whose planet surface the card is on, or the cardId of a facility the ship is docked at
>*   "Placed on" mission - new in this PR; cardId of the mission the card is placed on top of

This reply assumes we use a flat GameState JSON from the comment above.

I'm not sure "stacked" is useful. Two missions at the same location can be z-order determined by order provided in the missions array. The later item with the same ID would get stacked on top of the first one by the UI.

Do we have a list of the ways cards can be "attached to", "placed on", or otherwise affect each type of card? This would probably be a pretty big list / matrix.  That might help separate the words we would use to define the relationships between cards.

**Comment by datanoh** [comment]
@andrewd18 Sure, I think in general we're on the same page there. I'm thinking more about short-term application. The client has already been getting "attached" and "stacked" from the server (and have been since before you came on the project).

Does getting "placed on mission" as described in [the comment above](https://github.com/trekcc-ops/gemp-stccg/pull/125#issuecomment-2558525063) work for you for now? Or would you prefer to get this tightened up in some way for MVP? Either integrating it better into the JSON gamestate, or using some other sort of communication?

**Comment by andrewd18** [comment]
> The "place on mission" info is still coming through the game event classes. Any game event that includes the card data will include the attribute "placedOnMission" if the card is placed on a mission, with the parameter set to true. The "targetCardId" attribute in those cases will be the cardId of the top mission card for the location.
> 
> Ideally this would be caught for the "put card into play" and "move card" game animations on the client side.
Sure, if placedOnMission is true, use the targetCardId to determine where and then ~~steal~~ copy its absolute position to display it.

**Comment by datanoh** [comment]
> I'm not sure "stacked" is useful. Two missions at the same location can be z-order determined by order provided in the missions array. The later item with the same ID would get stacked on top of the first one by the UI.
> 
> Do we have a list of the ways cards can be "attached to", "placed on", or otherwise affect each type of card? This would probably be a pretty big list / matrix. That might help separate the words we would use to define the relationships between cards.

I'm good without "stacked" if you are. Is the client currently relying on it?

For "attached to" - this is a server/client communication property, with no exact analog in the actual game. The current applications are:
- cards aboard a ship or facility are attached to the ship or facility card
- cards on a planet surface are attached to the mission card
- ships docked at a facility are attached to the facility card


For the actual in-game 1E applications for how cards relate to each other, I believe it's mostly the following cases:
- cards seeded under a mission or Empok Nor, to be encountered during an attempt
- cards placed under another card that are explicitly not in play (The Nexus, Bluegill Infestation, Temporal Benefactor, etc.)
- cards placed under another card as part of a side deck, or side-deck-ish construct (Q's Tent, Battle Bridge Door, Watch Dog, Zalkonian Storage Capsule, Deliberately Discarded, etc.)
- cards placed on top of another card - Just about every card type can have another card explicitly "placed" on it for some reason or another. This would also likely be how we'd implement cards that play or seed on another card. (Friendly Fire, Birth of "Junior", Frame of Mind, Launch Portal, Cowboy Diplomacy, etc.)
- cards that are explicitly attached to a personnel or "worn" by them (Data's Body, Mobile Holo-Emitter, etc.) - I think these are functionally identical to the "place on top of another card" cases
- piles of cards (The Arsenal: Separated, personnel battle combat piles)
- cards aboard a ship or facility (including carried ships)
- ships docked at a facility
- cards at a site (including personnel, equipment, and docked ships)
- cards on a planet's surface (including personnel, equipment, landed ships, and planet facilities)

There's a couple other card relations that wouldn't typically involve the cards physically touching IRL:
- corresponding missions & time locations
- sites at a facility
- cards in space at a location

**Comment by andrewd18** [comment]
> I'm good without "stacked" if you are. Is the client currently relying on it?
No, you just took that code out. ;)

How the UI handles positioning of shared missions, cards-under-other-cards, etc. is still somewhat of a mystery to me. It's all buried in that absolute positioning code and split across dozens of files. My gut says it has something to do with jCardGroup.

I can hack together some z-index stuff for one card on a mission, but I don't know if I could handle two cards on top of a mission. Really the whole thing needs a rewrite, or at least a billion new unit tests, and that's before it goes to React. :cry:

**Comment by andrewd18** [comment]
> For the actual in-game 1E applications for how cards relate to each other, I believe it's mostly the following cases:

Save this list for later; assuming we get sanctioning past MVP I'm going to want to talk each of these through with my UX specialist.

**Comment by datanoh** [comment]
> No, you just took that code out. ;)

Haha I kinda did... but not entirely. More details below.

> How the UI handles positioning of shared missions, cards-under-other-cards, etc. is still somewhat of a mystery to me. It's all buried in that absolute positioning code and split across dozens of files. My gut says it has something to do with jCardGroup.

Ooh! I know this one. You're mostly right. The jCardGroups dictate how cards are laid out visually within a div. TL;DR: All the 1E UI visual layout of attached cards is handled by NormalCardGroup and TableCardGroup, and you can find the specific logic by searching for "attached" within those classes. (More on shared missions and cards-under-other-cards below this list.)
- VerticalBarGroup - No longer in use, feel free to delete. This was used for the "sites" part of the LotR deck builder.
- NormalCardGroup - Most card groups. Cards are laid out left to right, top to bottom. Attached cards are placed underneath the card they're attached to, and a little to the right. This is the same implementation you see in the deck builder. In the deck builder, if you have more than one copy of a card, all the subsequent copies are "attached".
- PlayPileCardGroup - I created this, and it's only used in Tribbles. The goal was to visually create a stack of cards that got a little bigger as cards were added to it. There are almost certainly better ways to implement this. For now the Tribbles UI does rely on it, but that can be changed easily.
- NormalGameCardGroup - I created this. It's the group for cards "played on table". No visual distinction between this and NormalCardGroup. I built this because all the cardGroups have a function parameter to determine if cards belong to it (joy...) and I couldn't figure out how to build a new function that included playerId.
- TableCardGroup - Everything on the spaceline. I added this, but it borrows heavily from SW Gemp. In this card group, attached cards are placed underneath and a little to the top. (This is what you see with Away Teams on a planet, or personnel aboard a ship.)
- MissionCardGroup - I created this. It's not currently in use. The point was visualizing shared missions. It seemed to do that correctly, but I didn't do a lot of testing. It doesn't have any logic for laying out "attached" cards, so I moved missions to TableCardGroup to show Away Teams as attached. I haven't revisited this in nearly a year.

**Shared missions** - These are still "stacked" on each other. They just don't use the "STACKED" zone (and I don't think they ever did). The top card is "stacked on" the bottom card on the server side, and when the top card is passed to the client in a "put card into play" event, the "targetCardId" is the bottom card. (This relation is also included in the serialized game state.) I suspect nothing on the client side is looking at this information for shared missions, though. And there are better ways to implement it.

**Cards underneath** - Personnel, ships, and equipment are all sent to the client as "attached" if they are aboard a ship/facility, docked at a facility, or on a planet surface. The only other kind of "underneath" that Gemp knows is cards seeded under a mission. For now, these are sent to Zone.VOID (so that they aren't shown at all in the UI), and also added to the "cardsSeededUnderneath" member of the mission location.

> I can hack together some z-index stuff for one card on a mission, but I don't know if I could handle two cards on top of a mission. Really the whole thing needs a rewrite, or at least a billion new unit tests, and that's before it goes to React. 😢

How tall of an order would that be? I could make immediate use of placing cards on missions, ships, and/or personnel. If it's limited to only one, that'd still be useful. If it's not in the cards for now (ha), that's fine too. Just let me know.

**Pull request merged**
