### PR TITLE
Docker build speedup and death to nohup.log

### LINKED ISSUE #113: Docker compose takes a few minutes
Due to a lack of caching, the Docker compose step can take a few minutes even if you've only modified one file.

Some improvements we can make:
- Don't re-download the docker base images from DockerHub unless they're actually out of date
- Mount the .m2 folder so Maven builds can reuse build cache from a previous run

### PR DESCRIPTION
**Pull request by andrewd18**
### Summary of Changes
Switch gemp-app docker container to a multi-phase build for better dependency caching.

All maven commands happen in a build phase
 - Use latest official maven container, not locked to 3.8.8
 - Use maven dependency module's go-offline command to cache the .m2 folder.
 - Use cache mounting for all subsequent mvn commands to ensure we use that cache.

Second phase is just for the runtime dependencies
 - Only copy the compiled .jar file to the final runtime image
 - Skip all the other apk dependency calls since they are obsolete by official maven container.
 - Use apk update and upgrade to ensure any other internals get updated for security patches.

### Benefits
- Java maven dependencies are cached.
- Build container runs faster thanks to the caching.
- Runtime docker container is smaller and faster to build.
- Removes nohup.log in favor of 3 new log files that are auto-created at runtime.
- Closes #113 

### Risks
- I break the build entirely. Mitigated by testing.

### Testing
The first build will take a while, as usual. Then make a change in the Java and rebuild. You should see noticeable speedups in the build phase, as the Java dependencies should be auto-cached.

### CODE REVIEW

**Comment by datanoh** [comment]
Hm. I got this error. Any ideas what's causing it?

>  => ERROR [build runtime 2/6] RUN apk update                                                                      14.7s
[build runtime 2/6] RUN apk update:
0.845 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz
2.453 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz
8.642 fetch https://apk.corretto.aws/x86_64/APKINDEX.tar.gz
13.64 WARNING: updating and opening https://apk.corretto.aws: temporary error (try again later)
14.03 v3.20.3-440-gfd1129d1e18 [https://dl-cdn.alpinelinux.org/alpine/v3.20/main]
14.03 v3.20.3-443-gbadabedaf8d [https://dl-cdn.alpinelinux.org/alpine/v3.20/community]
14.03 2 unavailable, 0 stale; 24174 distinct packages available
failed to solve: process "/bin/sh -c apk update" did not complete successfully: exit code: 2

**Comment by andrewd18** [comment]
Yup:
13.64 WARNING: updating and opening https://apk.corretto.aws: temporary
error (try again later)

AWS must be doing some maintenance. You can safely comment those two apk
lines out in gemp_app.dockerfile for maven testing purposes.

**Review by datanoh — DISMISSED** [review]
It's a Christmas miracle! My compose build just ran in about 15 seconds. Thank you so much!

Edited to remove the "approve" here. The build runs very quickly, but I can't compose up the Docker image. I assume this is because I commented out the apk lines.

**Comment by andrewd18** [comment]
What happens when you try to compose up the image? Any particular set of error messages?

Because it's such a big change to the dockerfile, I also had problems switching between branches with and without it. I had to:

1. Outside the container, enter the gemp-module directory and run a `mvn clean` to clear out any stale local build data. You'd probably do this from inside IntelliJ.
2.  In Docker Desktop, delete all containers and all saved images.
3. Then run `docker compose up`.

I had to do this every time I switched between a branch with the new cached template and the older non-cached template.

**Comment by datanoh** [comment]
I followed those steps, but still getting the following error message.

> Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/run/desktop/mnt/host/d/GEMP/gemp-stccg/gemp-stccg/logs/nohup.out" to rootfs at "/nohup.out": mount /run/desktop/mnt/host/d/GEMP/gemp-stccg/gemp-stccg/logs/nohup.out:/nohup.out (via /proc/self/fd/7), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by andrewd18** [comment]
I am able to reproduce it. Very weird.

**Workaround:** In your logs directory, delete any nohup.out folders and create an empty nohup.out file, then run docker compose up.

**Comment by andrewd18** [comment]
Please retest at your earliest convenience; I think these issues are now
resolved.

**Review by datanoh — COMMENTED** [review]
Huge improvement to the build time!

Everything looks good from my end, except for the apk lines which I'm still commenting out on my end.

**Pull request merged**
